### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by InfinitaSalo** [wireapp/poll-bot#11]
Hello,

How exactly do I install this? I downloaded and unzipped the files, but I'm not sure what directory they need to be in or where to enter the service code. I've never tried to use external code within Wire before so I'm not sure how to proceed. Thanks!

**Comment by dkovacevic** [comment]
Hi,

you could use the Poll bot that is deployed and running inside Wire cloud. 
Notice that only Wire team users can use bots. If you already have a Wire team and you are the admin of that team then go to team settings, services tab and enter:
3131a0af-89d4-4569-b36d-50bcced4b1fb:163a422b-c314-4e34-95af-10b6b36cde18

as service code in order to enable Poll bot for your team members.

Once you have Poll bot enabled for your team go back to Wire app, opet people picker, services tab, select Poll bot and connect

Have fun!
